# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-28 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewID', models.IntegerField(unique=True)),
                ('date', models.DateField(auto_now=True)),
                ('comment', models.CharField(default='Default', max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('quality', models.IntegerField(default=0)),
                ('atmostphere', models.IntegerField(default=0)),
                ('avgRating', models.IntegerField(default=0)),
            ],
        ),
    ]
