# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-28 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WERapp', '0002_remove_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
